#ifndef __ProjektGFKRangeDialog__
#define __ProjektGFKRangeDialog__

/**
@file
Subclass of RangeDialog, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing RangeDialog */
class ProjektGFKRangeDialog : public RangeDialog
{
	protected:
		// Handlers for RangeDialog events.
		void AcceptRangeDialog( wxCommandEvent& event );
		void CloseRangeDialog( wxCommandEvent& event );
	public:
		/** Constructor */
		ProjektGFKRangeDialog( wxWindow* parent );
	//// end generated class members







};

#endif // __ProjektGFKRangeDialog__
